feat: replace moment.js to day.js
Haulmont/jmix-frontend pull request #239
Opened 2021-04-22 07:29 UTC by HegelPro

affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-core, @haulmont/jmix-react-ui

BREAKING CHANGE:
remove moment.js

2021-04-28 13:47 UTC, vyacheslav-pushkin requested changes

2021-04-28 13:47 UTC, vyacheslav-pushkin commented on packages/jmix-react-ui/src/ui/DatePicker.tsx
> +TimePicker.displayName = 'TimePicker';
Can we put it to `TimePicker` file?

2021-04-28 13:47 UTC, vyacheslav-pushkin commented on packages/jmix-react-ui/src/ui/table/DataTableIntervalFunctions.ts
> +  else throw new Error(`Expected 'last' or 'next' mode, encountered '${mode}' mode`)
We need to include to CONTRIBUTING.md that our code style requires curly braces and `;`. As a personal preference, I'd also not to use `else`:

```
if (...) {
  return ...;
}

if (...) {
  return ...;
}
```

2021-04-29 14:48 UTC, HegelPro commented on packages/jmix-react-ui/package.json
> +    "dayjs": "^1.10.4",
For CI we need to include `dayjs`, otherwise, CI will not have this library.

2021-04-29 15:23 UTC, vyacheslav-pushkin commented on packages/jmix-react-core/src/util/formats.ts
> +  offsetDateTime: [OFFSET_DATE_TIME_DATE_TRANSFER_FORMAT, DEFAULT_DATE_TIME_DISPLAY_FORMAT],
> https://github.com/Haulmont/jmix-frontend/issues/142#issuecomment-827359407

@web-devel Is it working as intended? Perhaps we should restrict backend to use a single format.

2021-04-29 15:38 UTC, vyacheslav-pushkin approved these changes

2021-04-30 08:42 UTC, merged