Ability to sort generators in custom order
Haulmont/jmix-frontend pull request #379
Opened 2021-06-08 10:14 UTC by agmitron

2021-06-08 13:05 UTC, web-devel requested changes

2021-06-08 13:05 UTC, web-devel commented on packages/jmix-front-generator/src/common/base-generator.ts
> +  index: number;
Let's make it options

2021-06-08 13:05 UTC, web-devel commented on packages/jmix-front-generator/package-lock.json
> +	"lockfileVersion": 1,
Please use npm 7 (it creates lock files v2)

2021-06-08 13:05 UTC, web-devel commented on packages/jmix-front-generator/src/init.ts
> +      // generators.push({name, options, params, description, iconPath, index});
Don't leave commented code (unless there is an exceptional reason for that)

2021-06-17 12:42 UTC, web-devel requested changes
Please fix the commit message (use `npm run commit`)
* it's feature, not refactor
* add ticket number
* add `affects` label

2021-06-22 05:07 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Haulmont/jmix-frontend?pullRequest=379) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Haulmont/jmix-frontend?pullRequest=379) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Haulmont/jmix-frontend?pullRequest=379) it.</sub>

2021-06-22 05:08 UTC, agmitron commented
> Please fix the commit message (use `npm run commit`)
> 
> * it's feature, not refactor
> * add ticket number
> * add `affects` label

Resolved.

2021-07-20 13:04 UTC, vyacheslav-pushkin approved these changes

2021-07-21 08:29 UTC, merged