WIP: start replace tslint by eslint
Haulmont/jmix-frontend pull request #594
Opened 2021-08-27 11:56 UTC by HegelPro

affects: @haulmont/jmix-react-core

2021-09-02 14:54 UTC, vyacheslav-pushkin requested changes

2021-09-02 14:54 UTC, vyacheslav-pushkin commented
@HegelPro also pls resolve the conflict

2021-09-03 06:00 UTC, HegelPro commented on packages/jmix-front-generator/package.json
> +    "build": "rimraf lib && npm run lint && tsc && tsc --project tsconfig.declarations.json && node scripts/copy-templates.js",
For me it works fast, it might have been cached in my environment. Need to compare in CI.

2021-09-03 06:19 UTC, HegelPro commented on packages/eslint-config-jmix-react/package.json
> +  "name": "eslint-config-jmix-react",
`eslint-config-...` it's the default pattern for eslint config names.

2021-09-03 06:35 UTC, HegelPro commented on packages/jmix-front-generator/package.json
> +    "build": "rimraf lib && npm run lint && tsc && tsc --project tsconfig.declarations.json && node scripts/copy-templates.js",
I don't see any difference in CI. This RP lasted 18m in the pipeline, the last one in master lasted 22m.

2021-09-03 07:22 UTC, vyacheslav-pushkin commented on packages/eslint-config-jmix-react/package.json
> +  "name": "eslint-config-jmix-react",
OK

2021-09-03 07:22 UTC, vyacheslav-pushkin commented on packages/jmix-front-generator/package.json
> +    "build": "rimraf lib && npm run lint && tsc && tsc --project tsconfig.declarations.json && node scripts/copy-templates.js",
I'm more interested in local build with lint vs local build without lint.

2021-09-03 07:38 UTC, HegelPro commented on packages/jmix-front-generator/package.json
> +    "build": "rimraf lib && npm run lint && tsc && tsc --project tsconfig.declarations.json && node scripts/copy-templates.js",
I think, that eslint plugin for webpack has problems with performance. But eslint util works fast

2021-09-03 08:07 UTC, vyacheslav-pushkin approved these changes

2021-09-03 08:07 UTC, merged