feat: implement localesStore with support adding locales from externa…
Haulmont/jmix-frontend pull request #598
Opened 2021-08-31 06:06 UTC by karandashovrz

…l packages #82

affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-antd, @haulmont/jmix-react-web

2021-08-31 07:33 UTC, vyacheslav-pushkin approved these changes

2021-08-31 07:33 UTC, vyacheslav-pushkin commented on example-react-app/src/i18n/i18nInit.ts
> +  localesStore.addLocale({
We need a new line here

2021-08-31 08:40 UTC, vyacheslav-pushkin requested changes

2021-08-31 08:40 UTC, vyacheslav-pushkin commented on packages/jmix-front-generator/src/generators/react-typescript/app/template/src/i18n/i18nInit.ts.ejs
> +  <% if (isLocaleUsed('ru')) { -%>
Same problem with newline here.

2021-08-31 08:40 UTC, vyacheslav-pushkin commented on packages/jmix-front-generator/src/generators/react-typescript/app/template/src/i18n/i18nInit.ts.ejs
> +  <% } -%>
Just noticed that `cn-zh` locale is missing.

Also, let's imagine we want to add a new locale out-of-the-box. We will add a new `.json` file and add an entry to `SUPPORTED_CLIENT_LOCALES`. Ideally that should be it. How can we avoid having to put any new locale manually into this file?

2021-09-01 04:33 UTC, karandashovrz commented on packages/jmix-front-generator/src/generators/react-typescript/entity-editor/write.ts
> +  );
This call add dynamic keys

2021-09-01 07:30 UTC, vyacheslav-pushkin approved these changes

2021-09-01 07:30 UTC, merged