fix: add key navigation for tab, breadcrumbs and for some grid
Haulmont/jmix-frontend pull request #836
Opened 2021-12-06 10:06 UTC by deanex

affects: @haulmont/jmix-front-generator, @haulmont/jmix-react-antd, @haulmont/jmix-react-web,
test-puppeteer

Add key navigation
Change wrong test extensions
Single responsibility for MultiScreenBoundary

2021-12-06 12:13 UTC, vyacheslav-pushkin requested changes

2021-12-06 12:13 UTC, vyacheslav-pushkin commented on packages/jmix-react-web/src/ui/MultiScreen/styles.module.less
> +
Let's use the outline instead of color change.

2021-12-07 10:39 UTC, deanex commented on packages/jmix-react-antd/src/ui/Tabs/index.tsx
> +    <Tabs activeKey={tabs.currentTab?.key} onChange={onTabChange} locale={{removeAriaLabel: "close"}}>
This property unintentionally left - it's working for `closeIcon` prop which we don't use, instead we render whole tab with the title and close button in one place

2021-12-08 08:00 UTC, vyacheslav-pushkin approved these changes

2021-12-08 08:00 UTC, merged