feat: login error info message
Haulmont/jmix-frontend pull request #90
Opened 2021-01-29 14:01 UTC by HegelPro

affects: @haulmont/jmix-front-generator, @haulmont/jmix-rest

Show addition information about Login errors

2021-02-09 07:09 UTC, web-devel commented
please rebase on master

2021-02-09 08:06 UTC, HegelPro commented
> please rebase on master

I did it. But CI failed with a strange error

2021-02-10 08:32 UTC, web-devel requested changes

2021-02-10 08:32 UTC, web-devel commented on packages/jmix-front-generator/src/generators/react-typescript/app/template/src/app/login/Login.tsx
> +        const intlMessageId = mapJmixRestErrorToIntlId(
Let's try to reduce amount of code in template (user app)

2021-03-17 08:41 UTC, web-devel approved these changes

2021-03-18 13:18 UTC, merged